/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tremornetbeans;

import java.awt.Point;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.JTextArea;
import javax.swing.JViewport;

/**
 *
 * @author Kirjsten
 */
public class Events extends javax.swing.JFrame {

    List<Tremor> tremList;
    Sort sort;
    /**
     * Creates new form SortGUI
     */
    public Events(Sort sortPass) {
        initComponents();
        sort = sortPass;
        
        sortText = new JTextArea();
        sortText.setText(sort.sortSrt());
        sortText.setCaretPosition(0);
        eventsScrollPane.setViewportView(sortText);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eventsScrollPane = new javax.swing.JScrollPane();
        sortText = new javax.swing.JTextArea();
        saveButtonFile = new javax.swing.JLabel();
        dateButton = new javax.swing.JLabel();
        hrButton = new javax.swing.JLabel();
        movementButton = new javax.swing.JLabel();
        lengthButton = new javax.swing.JLabel();
        eventsBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eventsScrollPane.setBorder(null);

        sortText.setColumns(20);
        sortText.setRows(5);
        eventsScrollPane.setViewportView(sortText);

        getContentPane().add(eventsScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 750, 300));

        saveButtonFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Save Button.png"))); // NOI18N
        saveButtonFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveButtonFileMouseClicked(evt);
            }
        });
        getContentPane().add(saveButtonFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 80, 40));

        dateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Date Button.png"))); // NOI18N
        dateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateButtonMouseClicked(evt);
            }
        });
        getContentPane().add(dateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, 40));

        hrButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/HR Button.png"))); // NOI18N
        hrButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hrButtonMouseClicked(evt);
            }
        });
        getContentPane().add(hrButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, -1, 40));

        movementButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Movement Button.png"))); // NOI18N
        movementButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                movementButtonMouseClicked(evt);
            }
        });
        getContentPane().add(movementButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, -1, 40));

        lengthButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Length Button.png"))); // NOI18N
        lengthButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lengthButtonMouseClicked(evt);
            }
        });
        getContentPane().add(lengthButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, -1, 40));

        eventsBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Events - Background.png"))); // NOI18N
        getContentPane().add(eventsBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 420));

        setSize(new java.awt.Dimension(820, 440));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButtonFileMouseClicked
        PrintWriter writer;
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.showSaveDialog(null);
            java.io.File f = chooser.getSelectedFile();
            String filename = f.getAbsolutePath();
            writer = new PrintWriter(new FileWriter(filename+".csv"));
            writer.println("Date, Time, Max HR, Max Vector Magnitude, Length");
            tremList = sort.dateTime();
            for(int i =0; tremList.size()>i; i++)
            {
                Tremor trem = tremList.get(i);
                writer.println(trem.date()+","+trem.startTime()+","+trem.maxHR()+","+trem.maxVec()+","+trem.length());
            }
            writer.close();
        } catch (IOException ex) {
            Logger.getLogger(File.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane optionPane = new JOptionPane();
        optionPane.showMessageDialog(null, "File has been saved.", "File Saved", 1);

    }//GEN-LAST:event_saveButtonFileMouseClicked

    private void dateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateButtonMouseClicked
        tremList = sort.dateTime();
        sortText = new JTextArea();
        sort.print();
        sortText.setText(sort.sortSrt());
        eventsScrollPane.setViewportView(sortText);
    }//GEN-LAST:event_dateButtonMouseClicked

    private void hrButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hrButtonMouseClicked
       tremList = sort.heartRate();
       sortText = new JTextArea();
       sort.print();
       sortText.setText(sort.sortSrt());
       eventsScrollPane.setViewportView(sortText);
    }//GEN-LAST:event_hrButtonMouseClicked

    private void movementButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movementButtonMouseClicked
       tremList = sort.vectorMag();
       sortText = new JTextArea();
       sort.print();
       sortText.setText(sort.sortSrt());
       eventsScrollPane.setViewportView(sortText);
    }//GEN-LAST:event_movementButtonMouseClicked

    private void lengthButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lengthButtonMouseClicked
       tremList = sort.length();
       sort.print();
       sortText = new JTextArea();
       sortText.setText(sort.sortSrt());
       eventsScrollPane.setViewportView(sortText);
    }//GEN-LAST:event_lengthButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateButton;
    private javax.swing.JLabel eventsBackground;
    private javax.swing.JScrollPane eventsScrollPane;
    private javax.swing.JLabel hrButton;
    private javax.swing.JLabel lengthButton;
    private javax.swing.JLabel movementButton;
    private javax.swing.JLabel saveButtonFile;
    private javax.swing.JTextArea sortText;
    // End of variables declaration//GEN-END:variables
}
