/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tremornetbeans;

import java.awt.TextField;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Kirjsten
 */
public class Statistics extends javax.swing.JFrame {

    String meanPrint;
    /**
     * Creates new form Statistics
     */
    public Statistics(String mean) {
        initComponents();
        meanPrint = mean;
        
        statsTextArea = new JTextArea();
        statsTextArea.setText(meanPrint);
        statsTextArea.setCaretPosition(0);
        fileScrollPane.setViewportView(statsTextArea);

        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileScrollPane = new javax.swing.JScrollPane();
        statsTextArea = new javax.swing.JTextArea();
        saveButtonFile = new javax.swing.JLabel();
        fileBackground = new javax.swing.JLabel();

        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fileScrollPane.setBorder(null);

        statsTextArea.setColumns(20);
        statsTextArea.setRows(5);
        statsTextArea.setText("efr\ngr\n\n\nb\nty\nuy\ntrgf\ne\nghju\nkik\nyut\nrse\nthy\njuki\ntk\nyrdt\nbsvecrg\ntrhyj\nuki\nkr\nytere\nw\nfgtbhyj\nukil\n\ntre\ngt\nbrhyjuol\n,utmy\nntebrve\ntbn\niutmfy\ntrvec\ntrbyntb\nrecrbt\nuymnt\nb");
        fileScrollPane.setViewportView(statsTextArea);

        getContentPane().add(fileScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 750, 300));

        saveButtonFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Save Button.png"))); // NOI18N
        saveButtonFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveButtonFileMouseClicked(evt);
            }
        });
        getContentPane().add(saveButtonFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 80, 40));

        fileBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Statistics Background.png"))); // NOI18N
        getContentPane().add(fileBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButtonFileMouseClicked
        try {JFileChooser chooser = new JFileChooser();
            chooser.showSaveDialog(null);
            java.io.File f = chooser.getSelectedFile();
            String filename = f.getAbsolutePath();
            PrintWriter writer =new PrintWriter(new FileWriter(filename+".csv"));
            writer.println(meanPrint);
            writer.close();
        } catch (IOException ex) {
            Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "File has been saved.", "File Saved",1);
    }//GEN-LAST:event_saveButtonFileMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fileBackground;
    private javax.swing.JScrollPane fileScrollPane;
    private javax.swing.JLabel saveButtonFile;
    private javax.swing.JTextArea statsTextArea;
    // End of variables declaration//GEN-END:variables
}
