/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tremornetbeans;

import java.awt.Cursor;
import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Kirjsten
 */
public class TremorGUI extends javax.swing.JFrame {

    ReadIn readIn = null;
    List<DataPerMin>  dataPerMinArray = new ArrayList<DataPerMin>();
    Threshold threshold = null;
    String dataPerMinString = "";
    String tremListStr="";
    Overall overall;
    
    /**
     * Creates new form AppGUI
     */
    public TremorGUI() {
        initComponents();
        changeIcon();
    }

    public void changeIcon()
    {
        URL url = getClass().getResource("Icon.png");
         if (url != null) {
         ImageIcon icon = new ImageIcon(url);
         Image image = icon.getImage();
         this.setIconImage(image);
    } else {
        System.err.println("Couldn't find icon file");
    }
        
        
        
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterButton = new javax.swing.JLabel();
        fileNameCsv = new javax.swing.JTextField();
        fileButton = new javax.swing.JLabel();
        eventsButton = new javax.swing.JLabel();
        dailyEventsButton = new javax.swing.JLabel();
        statisticsButton = new javax.swing.JLabel();
        formatText = new javax.swing.JTextField();
        helpButton = new javax.swing.JLabel();
        clearButton = new javax.swing.JLabel();
        overallButton = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tremor Program");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Enter Button.png"))); // NOI18N
        enterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enterButtonMouseClicked(evt);
            }
        });
        getContentPane().add(enterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 120, -1, -1));

        fileNameCsv.setForeground(new java.awt.Color(153, 153, 153));
        fileNameCsv.setText("filename.csv");
        fileNameCsv.setBorder(null);
        fileNameCsv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fileNameCsvMouseClicked(evt);
            }
        });
        fileNameCsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileNameCsvActionPerformed(evt);
            }
        });
        getContentPane().add(fileNameCsv, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 310, 20));

        fileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/File Button.png"))); // NOI18N
        fileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fileButtonMouseClicked(evt);
            }
        });
        getContentPane().add(fileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 60, 40));

        eventsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Events Button.png"))); // NOI18N
        eventsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eventsButtonMouseClicked(evt);
            }
        });
        getContentPane().add(eventsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 80, 40));

        dailyEventsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Daily Events Button.png"))); // NOI18N
        dailyEventsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dailyEventsButtonMouseClicked(evt);
            }
        });
        getContentPane().add(dailyEventsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 130, 50));

        statisticsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Statistics Button.png"))); // NOI18N
        statisticsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statisticsButtonMouseClicked(evt);
            }
        });
        getContentPane().add(statisticsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 100, 50));

        formatText.setForeground(new java.awt.Color(153, 153, 153));
        formatText.setText("Format");
        formatText.setBorder(null);
        formatText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formatTextMouseClicked(evt);
            }
        });
        getContentPane().add(formatText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 100, 20));

        helpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Help button.png"))); // NOI18N
        helpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpButtonMouseClicked(evt);
            }
        });
        getContentPane().add(helpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 10, 70, 40));

        clearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Clear Button.png"))); // NOI18N
        clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearButtonMouseClicked(evt);
            }
        });
        getContentPane().add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 40));

        overallButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Overall Button.png"))); // NOI18N
        overallButton.setText("Overall");
        overallButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                overallButtonMouseClicked(evt);
            }
        });
        getContentPane().add(overallButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 70, 50));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Main - Background.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fileNameCsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileNameCsvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileNameCsvActionPerformed

    private void fileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileButtonMouseClicked
        if(readIn == null)
        {    
            JOptionPane.showMessageDialog(null, "Please enter in the file and format","File Needed",0);
        }else
        { 
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            for(int i =0; dataPerMinArray.size()>i; i++){
            DataPerMin dPM = dataPerMinArray.get(i);
            dataPerMinString += (dPM.date()+"\t"+dPM.time()+"\t"+dPM.axis1()+"\t"+dPM.axis2()+"\t"
                           +dPM.axis3()+"\t"+dPM.steps()+"\t"+dPM.HR()+"\t"+dPM.lux()+"\t"+dPM.iOff()
                           +"\t\t"+dPM.iStand()+"\t\t"+dPM.iSit()+"\t\t"+dPM.iLay()+"\t\t"+dPM.vec()+"\n");
            System.out.println(dPM.date());
            }
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            File file = new File(dataPerMinArray, dataPerMinString);
            file.setVisible(true);
        }
    }//GEN-LAST:event_fileButtonMouseClicked

    private void enterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterButtonMouseClicked
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        Boolean option = false;
        try{
            readIn = new ReadIn(fileNameCsv, formatText);
        }catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "File Not Found","404",0);
            Logger.getLogger(TremorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        readIn.read();  
        List dataPerMinArrayTemp = readIn.dataPerMinArray();
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        int response = JOptionPane.showConfirmDialog(null, "Do you want "
                     + "to enter another file?", "Enter Multiple Files",
                     JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            option = true;
            fileNameCsv.setText("Enter Next File Here");
            formatText.setText("Format");
        } else if(response == JOptionPane.NO_OPTION){
            option = false;
        }         
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        dataPerMinArray.addAll(dataPerMinArrayTemp);
        if(option == false){
            /**
            for(int i =0; dataPerMinArray.size()>i; i++){
            DataPerMin dPM = dataPerMinArray.get(i);
            dataPerMinString += (dPM.date()+"\t"+dPM.time()+"\t"+dPM.axis1()+"\t"+dPM.axis2()+"\t"
                           +dPM.axis3()+"\t"+dPM.steps()+"\t"+dPM.HR()+"\t"+dPM.lux()+"\t"+dPM.iOff()
                           +"\t\t"+dPM.iStand()+"\t\t"+dPM.iSit()+"\t\t"+dPM.iLay()+"\t\t"+dPM.vec()+"\n");
            System.out.println(dPM.date());
            }
            */
        }
        if(option == false){
            threshold = new Threshold(dataPerMinArray);
            threshold.setVisible(true);
        }
        overall = new Overall(readIn.overallDataArray());
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_enterButtonMouseClicked

    private void dailyEventsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dailyEventsButtonMouseClicked
       if(readIn==null)
       {
           JOptionPane.showMessageDialog(null, "Please enter in the file and format","File Needed",0);
       }else if(threshold == null)
       {
           JOptionPane.showMessageDialog(null, "No Threshold Entered", "Threshold?", 0);
       }else
       {
            DailyEvents dailyEvents  = new DailyEvents(threshold.tremDays(), readIn.overallDataArray());
            dailyEvents.setVisible(true);
       }
    }//GEN-LAST:event_dailyEventsButtonMouseClicked

    private void statisticsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statisticsButtonMouseClicked
     if(readIn == null)
     {
         JOptionPane.showMessageDialog(null, "Please enter in the file and format","File Needed",0);
     }else if(threshold == null)
     {
         JOptionPane.showMessageDialog(null, "No Threshold Entered", "Threshold?", 0);
     }else
     {    
         Statistics statistics = new Statistics(threshold.mean());
         statistics.setVisible(true);
     }
        
    }//GEN-LAST:event_statisticsButtonMouseClicked

    private void fileNameCsvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileNameCsvMouseClicked
       JFileChooser chooser = new JFileChooser();
       chooser.showOpenDialog(null);
        java.io.File f = chooser.getSelectedFile();
       String filename = f.getAbsolutePath();
       fileNameCsv.setText(filename);
    }//GEN-LAST:event_fileNameCsvMouseClicked

    private void eventsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventsButtonMouseClicked
    if(readIn == null)
    {
        JOptionPane.showMessageDialog(null, "Please enter in the file and format","File Needed",0);
    }else if(threshold == null)
    {
        JOptionPane.showMessageDialog(null, "No Threshold Entered", "Threshold?", 0);
    }else
    {    
        Sort sort = new Sort(threshold.tremList());
        sort.print();
        Events sortGUI = new Events(sort);
        sortGUI.setVisible(true);
    }
    }//GEN-LAST:event_eventsButtonMouseClicked

    private void helpButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpButtonMouseClicked
        new Help().setVisible(true);
    }//GEN-LAST:event_helpButtonMouseClicked

    private void clearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseClicked
       dataPerMinArray = new ArrayList<DataPerMin>();
       fileNameCsv.setText("filename.csv");
       formatText.setText("format");
    }//GEN-LAST:event_clearButtonMouseClicked

    private void formatTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formatTextMouseClicked
        formatText.setText("");
    }//GEN-LAST:event_formatTextMouseClicked

    private void overallButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_overallButtonMouseClicked
        overall.setVisible(true);
    }//GEN-LAST:event_overallButtonMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel clearButton;
    private javax.swing.JLabel dailyEventsButton;
    private javax.swing.JLabel enterButton;
    private javax.swing.JLabel eventsButton;
    private javax.swing.JLabel fileButton;
    private javax.swing.JTextField fileNameCsv;
    private javax.swing.JTextField formatText;
    private javax.swing.JLabel helpButton;
    private javax.swing.JLabel overallButton;
    private javax.swing.JLabel statisticsButton;
    // End of variables declaration//GEN-END:variables
}
